[package]
name = "rl"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "*"
bevy = { version = "*", features = ["wayland"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
